### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [rjlopez2/napari-omaas#41]
Hi @rjlopez2, while working on https://github.com/conda-forge/napari-omaas-feedstock/pull/2

We noticed that the following packages are used/imported in the source code but not listed as a requirement:
- matplotlib
- pandas
- requests
- scikit-image
- scipy

Could this be fixed fo the next release?

Cheer 🚀 !

**Comment by rjlopez2** [comment]
fixed for next release, thanks.
